name: Deploy stack

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: write
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
  
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (ONR dev ephemeral stacks)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::315037948697:role/infrastructure/service-deployment-integrations
          role-session-name: account_deploy_role
          aws-region: eu-west-1
      
      - name: Deploy stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: datadog-forwarder
          template: template.yaml
          parameter-overrides: "DdApiKeySecretArn=arn:aws:secretsmanager:eu-west-1:315037948697:secret:DDForwarderApiKey-gTHTwf,DdSite=datadoghq.com,FunctionName=datadog-forwarder"

